services:
  db:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geo123
      POSTGRES_DB: geoobra
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      ENV: prod
      LOG_LEVEL: info
      CORS_ALLOW_ORIGINS: https://app.geoobra.local
      JWT_SECRET: changeme
      JWT_ALG: HS256
      JWT_EXPIRES_MIN: 60
      DATABASE_URL: postgresql+psycopg://geo:geo123@db:5432/geoobra
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  db_data:
