services:
  db:
    image: postgis/postgis:16-3.4
    container_name: geoobra_db
    environment:
      POSTGRES_DB: geoobra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geoobra_api
    env_file:
      - .env.prod
    environment:
      # garante que uvicorn rode na porta correta do container
      PORT: 8000
      # fallback se env_file não definir
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM:-HS256}
      JWT_EXPIRES_MIN: ${JWT_EXPIRES_MIN:-43200}
      ENV: ${ENV:-production}
    command: >
      sh -c "
      python -m alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
