
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: geoobra
      POSTGRES_USER: geoobra
      POSTGRES_PASSWORD: geoobra
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geoobra -d geoobra"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: ./geoobra_backend_v3
    environment:
      DATABASE_URL: postgresql+psycopg2://geoobra:geoobra@db:5432/geoobra?sslmode=disable
      JWT_SECRET: change-me-in-prod
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      CORS_ALLOW_ORIGINS: http://localhost:5173,http://127.0.0.1:5173,*
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
